### PR TITLE
chore: updated docs to inlcude retry  options

### PR DESCRIPTION
**Pull request by thejoekingmann**

### CODE REVIEW

**Comment by thejoekingmann** [comment]
Small comment, this repo could really benefit from being apart of the original codebase instead of being separate. Since they are sharing types over, it takes extra effort to coordinate passing the correct build types instead of just using the current active one. I had to patch the package inside node_modules/@better-fetch to get the correct types over to the docs, it was not pretty
It's most definitely why the above build is failing too

**Comment by Bekacru** [comment]
> Small comment, this repo could really benefit from being apart of the original codebase instead of being separate. Since they are sharing types over, it takes extra effort to coordinate passing the correct build types instead of just using the current active one. I had to patch the package inside node_modules/@better-fetch to get the correct types over to the docs, it was not pretty It's most definitely why the above build is failing too

thanks again and yeah I'll move it to a monorepo one of these days.

**Comment by Bekacru** [comment]
also btw do I know you? please dm on telegram if you know my handle or twitter (https://twitter.com/imbereket).

**Comment by Bekacru** [comment]
@thejoekingmann Sorry to bother you again, but could you please move this PR to the main repo now that the doc is there?

**Comment by Bekacru** [comment]
hey @thejoekingmann please open this pr on the main repo as soon as possible. I'm going to release v1.1 once this is merged. I'll close it from this repo.

**Pull request closed without merging**
